spring:
  application:
    name: core

  datasource:
    name: fish
    url: jdbc:mysql://113.44.133.43:3306/fish
    username: bamboo
    password: buaagxz123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  rabbitmq:
    host: 113.44.133.43
    port: 5672
    username: bamboo
    password: buaagxz123
    listener:
      simple:
        acknowledge-mode: manual # 开启手动ACK，以使用channel.basicAck

  data:
    redis:
      host: 113.44.133.43
      port: 6379
      password: buaagxz123
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          max-wait: -1ms
          min-idle: 1
  cache:
    type: redis
    redis:
      time-to-live: 30m
      cache-null-values: false
      use-key-prefix: true
      key-prefix:
    cache-names: users,products,orders



bamboo:
  rabbitmq:
    host: 113.44.133.43
    port: 5672
    virtualHost: /
    username: bamboo
    password: buaagxz123
    queue: book
